### ISSUE TITLE
Error: Callback was already called

### ISSUE THREAD

**Issue by dlinnemeyer** [apigee-127/swagger-tools#233]
I've been using validate to error-check a swagger document and ran into a wall. It worked great at first, but after fixing a number of issues, I started getting the following error:

```
/usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:30:31
    at /usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:248:21
    at getDocument (/usr/lib/node_modules/swagger-tools/bin/swagger-tools:78:7)
    at /usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:246:17
    at /usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:122:13
    at _each (/usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:46:13)
    at async.each (/usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:245:13)
    at Object.map (/usr/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:216:23)
    at getDocuments (/usr/lib/node_modules/swagger-tools/bin/swagger-tools:90:9)
```

I dug around the code a bit and was able to console.log what I thought was the error triggering the callback problem. This seemed to be coming from getDocument's call to parseContent? 

```
Uncaught TypeError: Cannot read property 'name' of undefined
```

This is the yaml:

```
swagger: '2.0'
info:
  title: GIS API
  description: |
    Microservice API that handles geospacial mappings and renderings of
    EMSI data.
  version: "0.1.0"
host: localhost
schemes:
  - http
  - https
basePath: /
consumes:
  - application/json
produces:
  - application/json

paths:
  /:
    get:
      summary: Get list of countries available
      description: |
        Returns a list of available country codes. Country codes can be used
        to get subquent meta information about a given country.
      responses:
        200:
          description: A list of country codes
          schema:
            properties:
              countries:
                type: array
                items:
                  type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}:
    get:
      summary: Supported levels and versions
      description: |
        Returns all info required to query a given country. This includes
        available versions of that country's gis data, plus all levels
        in its region hierarchy.
      responses:
        200:
          description: levels and versions for a given country
          schema:
            properties:
              levels:
                type: array
                items:
                  type: string
              versions:
                type: array
                items:
                  type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/withinProximity:
    post:
      summary: Get codes within proximity of a point
      description: |
        The withinProximity endpoint returns a list of codes that
        lie within a specifed radius of a point. The code's level
        and hierarchy are determined by the meta information in the
        url path.
      parameters:
        - $ref: '#/parameters/Centroid'
        - $ref: '#/parameters/Radius'
      responses:
        200:
          description: A slice of codes
          schema:
            $ref: '#/definitions/Slice'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/closest:
    post:
      summary: Get closest code to point
      description: |
        The closest endpoint returns the code that is closest to the
        specified point. The code's level and hierarchy are determined
        by the meta information in the url path.
      parameters:
        - $ref: '#/definitions/Lat'
        - $ref: '#/definitions/Long'
      responses:
        200:
          description: A slice of codes
          schema:
            $ref: '#/definitions/Slice'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/contains:
    post:
      summary: Get the code that contains a point
      description: |
        The contains endpoint returns the code that contains the
        specified point. The code's level and hierarchy are determined
        by the meta information in the url path.
      parameters:
        - $ref: '#/definitions/Lat'
        - $ref: '#/definitions/Long'
      responses:
        200:
          description: A slice of codes
          schema:
            $ref: '#/definitions/Slice'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/centroid:
    post:
      summary: Get the centroid of a list of codes
      description: |
        The centroid endpoint returns a point that is the centroid of
        the list of specified codes.
      parameters:
        - $ref: '#/parameters/Codes'
      responses:
        200:
          description: The centroid
          schema:
            $ref: '#/definitions/Centroid'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/mbr:
    post:
      summary: Get the MBR of a list of codes
      description: |
        The mbr endpoint returns a rectangle that is the MBR of
        the list of specified codes.
      parameters:
        - $ref: '#/parameters/Codes'
      responses:
        200:
          description: The MBR
          schema:
            $ref: '#/definitions/Rectangle'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/mbc:
    post:
      summary: Get the MBC of a list of codes
      description: |
        The mbc endpoint returns a circle that is the MBC of
        the list of specified codes.
      parameters:
        - $ref: '#/parameters/Codes'
      responses:
        200:
          description: The MBC
          schema:
            $ref: '#/definitions/Circle'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/svg:
    post:
      summary: Get the svg paths of a list of codes
      description: |
        The svg endpoint returns svg paths corresponding to the
        geospacial boundaries of the list of specified codes. If
        aggregated, all the boundaries are collected into a single
        path.
      parameters:
        - $ref: '#/parameters/Codes'
        - $ref: '#/parameters/Aggregate'
      responses:
        200:
          description: A svg paths
          schema:
            properties:
              svg:
                type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/topojson:
    post:
      summary: Get a topoJSON object of a list of codes
      description: |
        The topojson endpoint returns a topoJSON object that contains the
        boundaries of the list of specified codes. If aggregated, all the
        boundaries are collected together inside the topoJSON object.
      parameters:
        - $ref: '#/parameters/Codes'
        - $ref: '#/parameters/Aggregate'
      responses:
        200:
          description: A topoJSON object
          schema:
            properties:
              topojson:
                type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{country}/{version}/{level}/geojson:
    post:
      summary: Get a geoJSON object of a list of codes
      description: |
        The geojson endpoint returns a geoJSON object that contains the
        boundaries of the list of specified codes. If aggregated, all the
        boundaries are collected together inside the geoJSON object.
      parameters:
        - $ref: '#/parameters/Codes'
        - $ref: '#/parameters/Aggregate'
      responses:
        200:
          description: A geoJSON object
          schema:
            properties:
              geojson:
                type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

parameters:
  Codes:
    name: codes
    in: body
    required: true
    description: A list of codes
    schema:
      type: array
      items:
        type: string
  Aggregate:
    name: aggregate
    in: body
    description: Collect all codes into a single path
    schema:
      type: boolean
      default: false
  Lat:
    name: lat
    in: body
    required: true
    description: Latitude
    schema:
      type: number
      format: double
  Long:
    name: long
    in: body
    required: true
    description: Longitude
    schema:
      type: number
      format: double
  Centroid:
    name: centroid
    in: body
    required: true
    description: Center point
    schema:
      $ref: '#/definitions/Point'
  Radius:
    name: radius
    in: body
    required: true
    description: radius, in miles
    schema:
      type: number
      format: double

definitions:
  Point:
    properties:
      lat:
        type: number
        format: double
        description: Latitude
      long:
        type: number
        format: double
        description: Longitude
  Rectangle:
    properties:
      topLeft:
        $ref: '#/definitions/Point'
        description: Top left corner of the rectangle
      bottomRight:
        $ref: '#/definitions/Point'
        description: Bottom right corner of the rectangle
  Circle:
    properties:
      centroid:
        $ref: '#/definitions/Point'
        description: Center point of the circle
      radius:
        type: number
        format: double
        description: The radius of the circle
  Slice:
    properties:
      hierarchyId:
        type: string
        description: |
          Id describing a code's dimension, country, and version.
      level:
        type: string
        description: A code's dimension level.
      codes:
        type: array
        items:
          type: string
        description: Codes decribed by hierarchyId and level.
  Error:
    properties:
      status:
        type: string
        description: The HTTP status code applicable to this problem
      code:
        type: string
        description: An application-specific error code
      title:
        type: string
        description: A short human-readable summary of the problem
      detail:
        type: string
        description: |
          A human-readable explanation specific to this occurrence
          of the problem
```

**Comment by dlinnemeyer** [comment]
I was able to get intelligible errors again when I fixed the parameter references from #/definitions/Lat and #/definitions/Long to #/parameters/Lat and #/parameters/Long. So for some reason the validator wasn't able to tell me about the reference typo for a parameter.

I tried again with a misspelling referenced (switched parameters/Codes to parameters/Codes2) and got the same problem.

**Comment by whitlockjc** [comment]
Which version of swagger-tools?  Something like this was fixed in the last release.  Also, are you just running `swagger-tools validate {YOUR_FILE}`?

**Comment by whitlockjc** [comment]
I am able to reproduce it.  Let me see what is up.

**Comment by whitlockjc** [comment]
Well, referencing `#/definitions/Lat` when it's really at `#/parameters/Lat` would be a real problem.  When I change them, it works fine.  I can make swagger-tools a little more resilient and see where we end up.

**Comment by mohsen1** [comment]
I see in `/{country}/{version}/{level}/contains:` path you have parameters array pointing to `definitions` instead of `parameters` hash

```yaml
 /{country}/{version}/{level}/contains:
    post:
      summary: Get the code that contains a point
      description: |
        The contains endpoint returns the code that contains the
        specified point. The code's level and hierarchy are determined
        by the meta information in the url path.
      parameters:
        - $ref: '#/definitions/Lat'
        - $ref: '#/definitions/Long'
```

There is probably more bugs in this because it's still failing to validate in the editor.

**Comment by whitlockjc** [comment]
@mohsen1 Right but swagger-tools should handle this instead of throwing a runtime error.  I've fixed this in master and will release soon.

**Comment by dlinnemeyer** [comment]
Thanks. That sounds great.

And yeah, there are a ton more errors in that spec. After I got the parameters references working, I was able to work through everything without any more issues.

**Comment by mohsen1** [comment]
@whitlockjc totally right. I think a warning or error about invalid pointers is the best response here.

**Comment by whitlockjc** [comment]
It will be handled like any other missing reference.  Here is the output:

```
swagger-tools validate swagger.yaml                                                                                                                                  (0 jobs) jwhitlock@tough-mudder

API Errors:

  #/paths/~1{country}~1{version}~1{level}~1closest/post/parameters/0/$ref: Definition could not be resolved: #/definitions/Lat
  #/paths/~1{country}~1{version}~1{level}~1closest/post/parameters/1/$ref: Definition could not be resolved: #/definitions/Long
  #/paths/~1{country}~1{version}~1{level}~1contains/post/parameters/0/$ref: Definition could not be resolved: #/definitions/Lat
  #/paths/~1{country}~1{version}~1{level}~1contains/post/parameters/1/$ref: Definition could not be resolved: #/definitions/Long
  #/paths/~1{country}~1{version}~1{level}~1centroid/post/responses/200/schema/$ref: Definition could not be resolved: #/definitions/Centroid
  #/paths/~1{country}/get: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1withinProximity/post/parameters/1: API has more than one body parameter
  #/paths/~1{country}~1{version}~1{level}~1withinProximity/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1withinProximity/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1withinProximity/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1closest/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1closest/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1closest/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1contains/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1contains/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1contains/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1centroid/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1centroid/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1centroid/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1mbr/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1mbr/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1mbr/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1mbc/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1mbc/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1mbc/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1svg/post/parameters/1: API has more than one body parameter
  #/paths/~1{country}~1{version}~1{level}~1svg/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1svg/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1svg/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1topojson/post/parameters/1: API has more than one body parameter
  #/paths/~1{country}~1{version}~1{level}~1topojson/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1topojson/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1topojson/post: API requires path parameter but it is not defined: level
  #/paths/~1{country}~1{version}~1{level}~1geojson/post/parameters/1: API has more than one body parameter
  #/paths/~1{country}~1{version}~1{level}~1geojson/post: API requires path parameter but it is not defined: country
  #/paths/~1{country}~1{version}~1{level}~1geojson/post: API requires path parameter but it is not defined: version
  #/paths/~1{country}~1{version}~1{level}~1geojson/post: API requires path parameter but it is not defined: level

API Warnings:

  #/parameters/Lat: Parameter is defined but is not used: #/parameters/Lat
  #/parameters/Long: Parameter is defined but is not used: #/parameters/Long

37 errors and 2 warnings
```
